### PR TITLE
Support Laravel 8

### PR DESCRIPTION
**Pull request by CasperLaiTW**

### CODE REVIEW

**Comment by neilherbertuk** [comment]
Could really do with Laravel 8 support....

**Comment by CasperLaiTW** [comment]
@neilherbertuk, you can try my fork before merged

**Comment by neilherbertuk** [comment]
> @neilherbertuk, you can try my fork before merged

Already using your fork :)

**Comment by Omranic** [comment]
Hello, thank you for your patience, this is now done! Check latest release!!

This package now supports Laravel v8, PHP v8, Composer v2, enjoy 🥳

CC @CasperLaiTW @neilherbertuk

**Pull request closed without merging**
