### PR TITLE
Add support laravel 6.0

### PR DESCRIPTION
**Pull request by rez1dent3**

### CODE REVIEW

**Comment by thijskok** [comment]
Any update on this, @Omranic? Looking forward to Laravel 6 support! 👍

**Comment by f00bar** [comment]
I'm also waiting on this @Omranic

**Comment by stefanius** [comment]
@Omranic I do not want to increase some pressure, but I hope that you can merge this very soon

**Comment by Omranic** [comment]
All packages are now updated, enjoy!
Thank you for your patience 🙂

**Pull request closed without merging**
